[package]
name = "xql-sqlx-mysql"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "MySQL backend for xql"

[dependencies]
sqlx = { version = "0.5", default-features = false, features = ["runtime-tokio-rustls", "mysql"] }
